deployment:
  initContainers:
  - name: fmp-volume-permission
    image: docker.io/busybox:latest
    imagePullPolicy: IfNotPresent
    command: ["sh", "-c", "mkdir -p /nexus-data && chown -R 200:200 /nexus-data"]
    securityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
      capabilities:
        add:
        - SYS_ADMIN
  
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  storageClass: "local-storage"
  storageSize: "10Gi"
  pv:
    name: "nexus-pv-volume"
    path: "/nexus-data"
    nodeAffinity:
      key: "kubernetes.io/hostname"
      value: "minikube-m02"
