controller:
  image: my-jenkins
  tag: 1.0.0
  imagePullPolicy: "IfNotPresent"
  serviceType: NodePort
  additionalPlugins:
    - docker-plugin:1.3.0
    - docker-workflow:563.vd5d2e5c4007f
    - maven-plugin:3.21
    - pipeline-maven:1293.v6c4d0ce54ee8

persistence:
  enabled: true
  existingClaim: jenkins-pv-claim
  storageClass: local-storage
  annotations: {}
  labels: {}
  accessMode: "ReadWriteOnce"
  size: "10Gi"
  volumes:
  mounts:

agent:
  podName: default
  customJenkinsLabels: default
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "2048Mi"
