controller:
  image: 192.168.49.2:32003/docker/my-jenkins
  tag: 1.0.1
  imagePullPolicy: "IfNotPresent"
  serviceType: NodePort
  nodePort: 32001
  additionalPlugins:
    - docker-plugin:1.5
    - docker-workflow:572.v950f58993843
    - maven-plugin:3.23
    - pipeline-maven:1331.v003efa_fd6e81
    - kubernetes:4029.v5712230ccb_f8 
  installPlugins:
    - configuration-as-code:1700.v6f448841296e

persistence:
  enabled: true
  existingClaim: jenkins-pv-claim
  storageClass: local-storage
  annotations: {}
  labels: {}
  accessMode: "ReadWriteOnce"
  size: "10Gi"
  volumes:
  mounts:

agent:
  podName: default
  customJenkinsLabels: default
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "2048Mi"
